---
title: "Table and Visuals"
format: html
editor: visual
---

```{r}
library(haven)
library(tidyverse)

brfssdata <- read_xpt("LLCP2023.XPT")
```

```{r}
#brfssdata <- brfssdata %>%
#rename(state= '_STATE')

brfssdata2 <- brfssdata %>%
  filter(state == 12) %>%
  select(GENHLTH, PHYSHLTH, MENTHLTH, POORHLTH, EDUCA, INCOME3, FLUSHOT7, SEXVAR, WEIGHT2) %>%
  na.omit() %>%
  mutate(GENHLTH=as.factor(GENHLTH)) %>%
  mutate(PHYSHLTH=as.factor(PHYSHLTH)) %>%
  mutate(MENTHLTH=as.factor(MENTHLTH)) %>%
  mutate(POORHLTH=as.factor(POORHLTH)) %>%
  mutate(EDUCA=as.factor(EDUCA)) %>%
  mutate(INCOME3=as.factor(INCOME3)) %>%
  mutate(FLUSHOT7=as.factor(FLUSHOT7)) %>%
  mutate(SEXVAR=as.factor(SEXVAR))
```

```{r}
#Histograms
hist(brfssdata$GENHLTH)
hist(brfssdata$PHYSHLTH)
hist(brfssdata$MENTHLTH)
hist(brfssdata$POORHLTH)
hist(brfssdata$EDUCA)
hist(brfssdata$INCOME3)
hist(brfssdata$FLUSHOT7)
hist(brfssdata$WEIGHT2)
```

```{r}
#Table
library(tableone)
table1 <- CreateTableOne(data = brfssdata)
print(table1)
```

```{r}
#More Advanced Table One

#Here I am transforming my columns to Categorical Variables and identifying my variables
catVars <- c("GENHLTH","EDUCA","FLUSHOT7","SEXVAR")
myVars <- c("GENHLTH","PHYSHLTH","MENTHLTH","POORHLTH","EDUCA","INCOME3","FLUSHOT7","SEXVAR")

#Making the table one now
table2 <- CreateTableOne(vars=myVars,data=brfssdata,factorVars = catVars)

#showing all levels of categorical variables
print(table2, showAllLevels = TRUE, formatOptions = list(big.mark=","))
```

```{r}
#Summary Table for table2
summary(table2)
```

```{r}
#Here I want to create a really complicated TableOne
table3 <- CreateTableOne(vars=myVars,strata="FLUSHOT7",data=brfssdata,factorVars=catVars)
print(table3,formatOptions=list(big.mark=","))
```

```{r}
#These are my models
library(quantreg)

m1 <- rq(brfssdata2$WEIGHT2~brfssdata2$GENHLTH+brfssdata2$PHYSHLTH+brfssdata2$MENTHLTH+brfssdata2$POORHLTH+brfssdata2$EDUCA+brfssdata2$INCOME3+brfssdata2$FLUSHOT7+brfssdata2$SEXVAR, data=brfssdata, tau = 0.25)

m2 <- rq(brfssdata2$WEIGHT2~brfssdata2$GENHLTH+brfssdata2$PHYSHLTH+brfssdata2$MENTHLTH+brfssdata2$POORHLTH+brfssdata2$EDUCA+brfssdata2$INCOME3+brfssdata2$FLUSHOT7+brfssdata2$SEXVAR, data=brfssdata, tau = 0.50)

m3 <- rq(brfssdata2$WEIGHT2~brfssdata2$GENHLTH+brfssdata2$PHYSHLTH+brfssdata2$MENTHLTH+brfssdata2$POORHLTH+brfssdata2$EDUCA+brfssdata2$INCOME3+brfssdata2$FLUSHOT7+brfssdata2$SEXVAR, data=brfssdata, tau = 0.75)
```
